
import = [
	# "~/.config/alacritty/catppuccin-latte.toml"
	# "~/.config/alacritty/catppuccin-frappe.toml"
	"~/.config/alacritty/catppuccin-macchiato.toml"
	# "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = true

[font]
size = 16.0

[font.normal]
family = "MesloLGS NF"

